# name: Metrics
# on:
#   schedule: 
#     - cron: "0 20 * * *"

#   workflow_dispatch:

# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: lowlighter/metrics@latest
#         with:
#           token: ${{ secrets.METRICS_TOKEN }}
          
#           plugin_wakatime: yes
#           plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

#           plugin_languages: yes
          
# #           plugin_anilist: yes
# #           plugin_anilist_user: alui20
# #           plugin_anilist_medias: anime

#           plugin_topics: yes
